version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456

  postfixadmin:
    depends_on:
      - db
    image: postfixadmin
    ports:
      - 8000:80
    restart: always
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: db
      POSTFIXADMIN_DB_USER: admin
      POSTFIXADMIN_DB_NAME: admin
      POSTFIXADMIN_DB_PASSWORD: 123456
