apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myd
  name: myd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myd
  template:
    metadata:
      labels:
        app: myd
    spec:
      containers:
      - image: deepak2007/apache_php
        name: apache-php
